import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import pp from '../../public/ben.jpg'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={`${styles.leftDiv}`}>
          <h1>Sol div</h1>
          <Image
            src={"/ben.jpg"}
            alt='Picture of the author'
            className={`${styles.profilePhoto}`}
            width={500}
            height={500}
          />
        </div>
        <div className={`${styles.rightDiv}`}>
          <h1>Sağ div</h1>
          <div className={`${styles.rightMenu}`}>
            <div className={`${styles.rightMenuDiv}`}>
              <div className={`${styles.rightMenuDivElements}`}>
                <h3>Projelerim</h3>
              </div>
              <div className={`${styles.rightMenuDivElements}`}>
                <h3>Hakkımda</h3>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
